# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  batch: true
  branches:
    include:
    - master
pool:
  vmImage: 'windows-latest'

variables:
- name: solution
  value: '**/*.slnx'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'
- name: NUGET.PLUGIN.HANDSHAKE.TIMEOUT.IN.SECONDS
  value: 60
- name: NUGET.PLUGIN.REQUEST.TIMEOUT.IN.SECONDS
  value: 60
- name: netVersion
  value: '10.x'
- name: releaseSuffix
  value:  ''

name: 3.0.$(date:yyMM).$(date:dd)$(rev:r)
steps:

- task: NuGetToolInstaller@1
  displayName: Install Latest Nuget

- task: UseDotNet@2
  displayName: 'Install .NET sdk'
  inputs:
    packageType: 'sdk'
    version: $(netVersion)

- task: Bash@3
  displayName: Restore Workloads
  inputs:
    targetType: 'inline'
    script: 
      dotnet workload restore
  
- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: 'restore'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --no-restore /p:Platform="$(buildPlatform) /p:Version=$(Build.BuildNumber)$(ReleaseSuffix) /p:AssemblyVersion=$(Build.BuildNumber) /p:FileVersion=$(Build.BuildNumber)'

- task: CopyFiles@2
  displayName: Copy Files to $(build.artifactstagingdirectory)
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/DSoft.*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts drop
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
