<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net10.0;net10.0-android;net10.0-ios;net10.0-maccatalyst;net10.0-macos;net10.0-tvos;</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0;net481;</TargetFrameworks>
        <!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
        <!-- <TargetFrameworks>$(TargetFrameworks);net10.0-tizen</TargetFrameworks> -->
<!--        <UseMaui>true</UseMaui>-->
<!--        <SingleProject>true</SingleProject>-->
        <LangVersion>Latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <Product>$(AssemblyName) ($(TargetFramework))</Product>
        <Configurations>Debug;Release</Configurations>
        <DebugType>portable</DebugType>
        <UseFullSemVerForNuGet>false</UseFullSemVerForNuGet>
        <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
        <RootNamespace>System.BluetoothLe</RootNamespace>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <PackageId>DSoft.System.BluetoothLe</PackageId>
        <Authors>newky2k</Authors>
        <PackageLicenseExpression>Apache-2.0+</PackageLicenseExpression>
        <Description>Cross-platform Bluetooth Low Energy library, based on Plugin.BLE, for .NET Android, .NET iOS, .NET macOS, .NET Mac Catalyst, .NET tvOS, .NET for Windows, .NET, .NET Standard, and .NET Framework 4.8.1.</Description>
        <AssemblyName>System.BluetoothLe</AssemblyName>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>DSoft.snk</AssemblyOriginatorKeyFile>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/newky2k/DSoft.System.BluetoothLe</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageProjectUrl>https://github.com/newky2k/DSoft.System.BluetoothLe</PackageProjectUrl>
        <PackageReleaseNotes>
            Migrated to .NET 10.0
        </PackageReleaseNotes>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>DSIcon.png</PackageIcon>
        <PackageTags>BluetoothLe dotnet android ios macos maccatalyst windows wpf netstandard tvos</PackageTags>
        <Copyright>Copyright © 2026 DSoft</Copyright>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'macos'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tvos'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
    </PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\DSIcon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
	
    <ItemGroup Condition=" '$(Configuration)'=='Release' And '$(OS)' == 'Windows_NT' ">
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All" />
    </ItemGroup>

    <PropertyGroup Condition=" $(TargetFramework.StartsWith('net481')) Or $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows' ">
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="**\*.shared.cs" />
        <Compile Include="**\*.shared.*.cs" />
    </ItemGroup>

    <ItemGroup Condition=" $(TargetFramework.StartsWith('netstandard')) Or '$(TargetFramework)' == 'net10.0' ">
        <Compile Include="**\*.netstandard.cs" />
        <Compile Include="**\*.netstandard.*.cs" />
    </ItemGroup>

    <ItemGroup Condition=" $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows' And !$(TargetFramework.StartsWith('net4')) ">
        <Compile Include="**\*.netcore.cs" />
        <Compile Include="**\*.netcore.*.cs" />
    </ItemGroup>

    <ItemGroup Condition=" $(TargetFramework.StartsWith('net481')) ">
        <PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.18362.2007" />
        <Compile Include="**\*.netf.cs" />
        <Compile Include="**\*.netf.*.cs" />
    </ItemGroup>

    <ItemGroup Condition=" $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android' ">
        <Compile Include="**\*.android.cs" />
        <Compile Include="**\*.android.*.cs" />
        <AndroidResource Include="Resources\xml\*.xml" />
    </ItemGroup>

    <ItemGroup Condition=" $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios' ">
        <Compile Include="**\*.ios.cs" />
        <Compile Include="**\*.ios.*.cs" />
    </ItemGroup>

    <ItemGroup Condition=" $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst' ">
        <Compile Include="**\*.ios.cs" />
        <Compile Include="**\*.ios.*.cs" />
    </ItemGroup>

    <ItemGroup Condition=" $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'macos' ">
        <Compile Include="**\*.mac.cs" />
        <Compile Include="**\*.mac.*.cs" />
    </ItemGroup>

    <ItemGroup Condition=" $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tvos' ">
        <Compile Include="**\*.tvos.cs" />
        <Compile Include="**\*.tvos.*.cs" />
    </ItemGroup>

</Project>
